apiVersion: apps/v1
kind: Deployment
metadata:
  name: obico-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obico
  template:
    metadata:
      labels:
        app: obico
    spec:
      containers:
      - name: obico
        image: koskit/obico-server:latest
        ports:
        - containerPort: 80
