apiVersion: v1
kind: Service
metadata:
  name: obico-server-ext
  namespace: default  # Ensure this matches the namespace where Prometheus is deployed
spec:
  type: NodePort
  selector:
    app: obico  # Ensure this matches the labels of your Prometheus pods
  ports:
    - protocol: TCP
      port: 3334
      targetPort: 3334
      nodePort: 30100  # You can specify a particular NodePort or let Kubernetes assign one
