apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-wyoming
  namespace: speech-recognition
  labels:
    app: whisper-wyoming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-wyoming
  template:
    metadata:
      labels:
        app: whisper-wyoming
    spec:
      containers:
      - name: whisper-wyoming
        image: rhasspy/wyoming-whisper:latest
        args:
          - "--model=tiny-int8"  # You can choose different model sizes
          - "--language=en"      # Specify language if needed
          - "--uri=tcp://0.0.0.0:10300"
        ports:
        - containerPort: 10300
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"