apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-whisper-pvc
  namespace: whisper
spec:
  accessModes:
    - ReadWriteOnce  #  Important:  Means the volume can be mounted by a single pod at a time.
  resources:
    requests:
      storage: 1Gi   #  ***CHANGE THIS*** to the amount of storage you need.  Start small.