apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper-service
  namespace: whisper
spec:
  type: NodePort
  selector:
    app: wyoming-whisper
  ports:
    - port: 10300
      targetPort: 10300
      nodePort: 30125  # You can choose a different port between 30000-32767
      