apiVersion: v1
kind: Service
metadata:
  name: whisper-wyoming
  namespace: speech-recognition
spec:
  selector:
    app: whisper-wyoming
  ports:
  - port: 10300
    targetPort: 10300
    nodePort: 30300  # Node port between 30000-32767
    protocol: TCP
  type: NodePort 