apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
  namespace: monitoring  # Ensure this matches the namespace where Prometheus is deployed
spec:
  type: NodePort
  selector:
    app: prometheus-prometheus  # Ensure this matches the labels of your Prometheus pods
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # You can specify a particular NodePort or let Kubernetes assign one

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
  namespace: monitoring  # Ensure this matches the namespace where Grafana is deployed
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana  # Ensure this matches the labels of your Grafana pods
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Exposing Grafana on NodePort 30080
