apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: home-assistant
spec:
  type: NodePort
  selector:
    app: samba
  ports:
    - port: 445
      targetPort: 445
      nodePort: 30445  # Choose an available port
      name: smb