apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
      server:
        service:
          type: NodePort  # Change to NodePort or LoadBalancer as needed
          port: 300090            # The port on which Prometheus will be accessible
          targetPort: 9090    # The port Prometheus listens on internally
