apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: '15.12.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
