apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
  namespace: monitoring  # Ensure this matches the namespace where Prometheus is deployed
spec:
  type: NodePort
  selector:
    app: prometheus  # Ensure this matches the labels of your Prometheus pods
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # You can specify a particular NodePort or let Kubernetes assign one


