apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
              name: http
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: TZ
              value: "Asia/Jerusalem"  # Change this to your timezone
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config