apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 30123  # You can choose a different port between 30000-32767
      name: http